name: Nusrat Kamal Siddiqui
favicon: null
layout_spectrum: 0.8470105766318738
typography_spectrum: 0.4646270079538226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.23910024692304432
  lightness: 0.9199143743608147
  saturation: 0.9820683072321117
  rhythmicContrast: 0.716692550573498
purpose: []
